### ISSUE TITLE
Ampersands in Query String Incorrectly Sanitized

### ISSUE THREAD

**Issue by GoogleCodeExporter** [m3m0ryh0l3/extracturl#1]
```
It seems that urls containing a query string with more than 1 key / value pair 
do not work correctly as the ampersands in the query string are being url 
encoded.

I've attached a sample file, if you run:
  ./extract_url.pl -l sample_email.txt

You can see an example of the query string being incorrectly encoded.

I've also attached a patch that solves the problem.

Thanks,
-Matt
```

Original issue reported on code.google.com by `matt.gar...@gmail.com` on 3 Nov 2013 at 7:11

Attachments:
- [sample_email.txt](https://storage.googleapis.com/google-code-attachments/extracturl/issue-1/comment-0/sample_email.txt)
- [0001-Don-t-santize-ampersands-in-uri.patch](https://storage.googleapis.com/google-code-attachments/extracturl/issue-1/comment-0/0001-Don-t-santize-ampersands-in-uri.patch)

**Comment by m3m0ryh0l3** [comment]
I pushed what I think might be a better fix, trying to adhere a little more closely to RFC 3986. Just put RAW_RESERVED in your config file.
