### ISSUE TITLE
Pound signs are incorrectly sanitized

### ISSUE THREAD

**Issue by GoogleCodeExporter** [m3m0ryh0l3/extracturl#2]
```
What steps will reproduce the problem?
1. Extract any URL that includes a '#' character, such as 
http://myurl.com/something#somethingelse

What is the expected output? What do you see instead?
The expected output is 'http://myurl.com/something#somethingelse'. Instead, 
extract_url produces the percent escape of the character 
'http://myurl.com/something%23somethingelse'.

This patch fixes the problem, and I think it's generally safe. I'm having 
trouble envisioning a situation where '#' would be inappropriate in an URL, 
breaking the shell:

diff --git a/extract_url.pl b/extract_url.pl
index 3d32a08..e20248e 100755
--- a/extract_url.pl
+++ b/extract_url.pl
@@ -229,7 +229,7 @@ sub renderuri {
 }
 sub sanitizeuri {
        my($uri) = @_;
-       $uri =~ s/([^a-zA-Z0-9_.!*()\@:=\?\/%~+-])/sprintf("%%%X",ord($1))/egs;
+       $uri =~ 
s/([^a-zA-Z0-9_.!*()\@:=\?\/%~+-\\#])/sprintf("%%%X",ord($1))/egs;
        return $uri;
 }
```

Original issue reported on code.google.com by `christiw...@gmail.com` on 23 Dec 2014 at 8:29

**Comment by m3m0ryh0l3** [comment]
Fair enough. Thanks for the fix!

**Comment by chdiza** [comment]
I must be doing something wrong.  It's still turning `#` into `%23`.

If I put `https://github.com/m3m0ryh0l3/extracturl/issues/2#issuecomment-127324370` into a file named `test`, and then do `extract_url test`, I get a 404 from GitHub because the pound sign got percented.

**Comment by chdiza** [comment]
However, setting `RAW_RESERVED` works.

I was under the impression that the patch for this issue is supposed to work even without `RAW_RESERVED` being set.

**Comment by m3m0ryh0l3** [comment]
I didn't take the patch exactly as submitted. Since there were multiple bugs that amounted to "please don't escape character X", I tried to come up with a more standard rationale behind what to escape and what to not escape. When I found RFC 3986, that gave me exactly what I was looking for.

**Comment by chdiza** [comment]
Oh, I see what happened now; I got confused.  This change came before, not after, the arrival of `RAW_RESERVED`, and so its repair of the `#` problem was quickly superseded by that of the new config setting.

BTW, thanks for fixing this issue!  I had previously resorted to manually patching my copy.
