### ISSUE TITLE
alt_select_key = "k" vs. vim-style navigation

### ISSUE THREAD

**Issue by yourealwaysbe** [m3m0ryh0l3/extracturl#4]
This project looks great and i have started to use it.

A small suggestion is that "k" is defined as an alternative key for selecting URLs.  However, j/k is a fairly standard alternative to down/up for navigation.  Currently,  j works for moving down the URL list, but k does not move up the list.  Personally i would prefer j/k to work as down/up and some other key (h?) be the alternative select.

**Comment by protist** [comment]
+1. The first thing I did was to rebind ALTSELECT so that k moved up again.

**Comment by m3m0ryh0l3** [comment]
Fixed in commit 7bb18aa
