### ISSUE TITLE
Increase number of surrounding characters in context view

### ISSUE THREAD

**Issue by protist** [m3m0ryh0l3/extracturl#5]
I'm not sure if this project has been abandoned, but I think the context mode could be improved. At the moment, it seems to surround `=>URL<=` with 30 characters of context on either side. It'd be very useful if extracturl could determine the size of the window, and increase the surrounding characters to the entire width of the window , while centring `=>URL<=`. Frequently, I find that 30+30 characters is not enough context for me to determine what the link is. My terminal is 210 characters wide, so there's a lot more room for it to expand.

In case there is no reply to this, and other are wondering where the number of characters are hard-coded, they are [here](https://github.com/m3m0ryh0l3/extracturl/blob/master/extract_url.pl#L284) and [here](https://github.com/m3m0ryh0l3/extracturl/blob/master/extract_url.pl#L289).

**Comment by m3m0ryh0l3** [comment]
It's not abandoned... just not really changed much (hasn't needed it).

I'll look into querying the available width. It may not be as easy as one would like.

**Comment by protist** [comment]
Sorry, I had just assumed it was abandoned based on the lack of response on the other issue, and your activity in the last year. (Thanks for extracturl, BTW, and I agree that it's certainly a very polished project!)

As far as querying terminal width, it's relatively straightforward with `tput cols`, or in [perl](http://stackoverflow.com/a/1782149). Then, the math should be fairly simple.

**Comment by m3m0ryh0l3** [comment]
Fixed by commit 4f4f0a640e5cebca08cc934bcbf25826f3188fd1

**Comment by protist** [comment]
This fix works well. Thank you again. It looks like you modified the format in some cases? Now I get a mixture of `<|URL|>` and `=>https://github.com<=`. I don't really mind, but I was just wondering what the different formats mean?

**Comment by m3m0ryh0l3** [comment]
Excellent - glad it works.
I was playing around with a way of displaying the URL that highlighted it a bit more. I found the `=>URL<=` to blend into generic text just a little too much.

**Comment by protist** [comment]
Fair enough. I don't really have a strong feeling either way. Thanks again for the fix!
