### ISSUE TITLE
Runtime error: "Can't locate sys/ioctl.ph in @INC"

### ISSUE THREAD

**Issue by jasonwryan** [m3m0ryh0l3/extracturl#6]
1.6.1 builds fine on Arch Linux against Perl 5.24.1, but when it is invoked, it errors out with:

> Can't locate sys/ioctl.ph in @INC (did you run h2ph?) (@INC contains: /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at /usr/bin/extract_url line 60.

Where 60 is: `require 'sys/ioctl.ph';` which does not appear to exist on Arch.

Running h2ph as part of the build script, like so:

`h2ph -d "${_realname}-${pkgver}" /usr/include/syscall.h`

makes no difference.

Am I missing something obvious?

**Comment by m3m0ryh0l3** [comment]
Hmmm, clearly I need to put that in a conditional better. You should be able to work around it by installing Term::ReadKey, though.

**Comment by jasonwryan** [comment]
Thanks for the quick follow up. I already have perl-term-readkey 2.37

**Comment by protist** [comment]
I can confirm that extracturl 1.6.1 fails to work for me, with the same error message. I also had perl-term-readkey 2.37 installed. (I'm also using Arch Linux.)

**Comment by m3m0ryh0l3** [comment]
Try the latest commit (fad68f298f3f2afd81c2c5694814f0f48b75556f). That should resolve the problem (I think). Let me know if that fixes it - if it does, I'll put together 1.6.2.

**Comment by protist** [comment]
That works fine for me now. Thank you for the quick fix.

**Comment by jasonwryan** [comment]
Thanks: that works great!
